### ISSUE TITLE
Delete book button won't work

### ISSUE THREAD

**Issue by mokuhasushi** [francisGolden/library#1]
Steps to reproduce:
 - add a book
 - click on delete button 
 - book isn't deleted

I think the issue is related to the button method. I suggest looking into the "splice" method of arrays
https://stackoverflow.com/questions/3596089/how-to-remove-specific-value-from-array-using-jquery
(The first solution is a couple of steps ahead, but there is an answer which uses splice)

**Comment by francisGolden** [comment]
fixed the delete book button in latest commit by using a forEach method on every "delete book" button and adding an event that removes its parent node
